- name: Create application directory
  become: true
  file:
    state: directory
    path:  "{{ phoenix_path }}/{{app_name}}"
    mode:  0777

- name: Install Phoenix
  shell: "mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v1.0.3/phoenix_new-1.0.3.ez --force"
  args:
    creates: "~/.mix/archives/phoenix_new-1.0.3.ez"

# - git: repo=ssh://git@github.com/TigerWolf/hello_phoenix.git dest="{{ phoenix_path }}/{{app_name}}" accept_hostkey=yes update=yes force=True
#   remote_user: "{{ phoenix_user }}"
