---
- hosts: app-servers
  remote_user: deployer
  accelerate: true # Temp
  vars_files:
    - vars/main.yml

  roles:
    # - {role: "HashNuke.elixir-stack", action: "deploy"}
    - {role: "~/dev/ansible-elixir-stack", action: "deploy"}
