---
- hosts: app-servers
  remote_user: root
  vars_files:
    - vars/main.yml

  roles:
    # - {role: "HashNuke.elixir-stack", action: "remove-app"}
    - {role: "~/dev/ansible-elixir-stack", action: "remove-app"}
