---
- hosts: app-servers
  remote_user: root
  vars_files:
    - vars/main.yml

  roles:
    - {role: "~/dev/ansible-elixir-stack", action: "setup"}
    # - { role: '/path/to/common/roles/foo', x: 1 }
